### ISSUE TITLE
[No Connection] App crashes when sharing file when offline.

### ISSUE THREAD

**Issue by Thusuzzee** [ZeldaFan0225/nekos.best#9]
**Descripe the bug as you would to a friend**
> When you don't have a connection the app crashes when clicking on the "Share as file" 

**Steps to reproduce**
> Disconnect Wi-Fi
> Open app
> Click on the share button or "Share as file"
> Observe

**What should happen**
> The app should not crash or should show a "No Connection" pop-up

**What actaully happens**
> The app crashes 

**Device information**
> Android 10

**Comment by ZeldaFan0225** [comment]
App now shows error that no image is loaded and that you should try again, app isnt crashing now
